services:
  - type: web
    name: mc-bot-manager
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: MC_HOST
        value: "play.gamerpointmc.qzz.io"
      - key: MC_PORT
        value: "25565"
      - key: MC_VERSION
        value: "1.21.11"
      - key: BOT_COUNT
        value: "1000"
      - key: RECONNECT_DELAY
        value: "10000"
      - key: PANEL_PASSWORD
        sync: false
      - key: BOT_NAMES
        value: "b_0t_17,bot39281,b0t_2,b0t_4737,batsk83,fjs_256"
      - key: JOIN_COMMAND
        value: ""
      - key: LOGIN_COMMAND
        sync: false
      - key: LOGIN_DELAY
        value: "2500"
